#!/bin/bash
# Generated by zfs_beskar_key v{{VERSION}}
set -euo pipefail

if ! command -v warn >/dev/null 2>&1; then
    warn() { echo "[BESKAR] ${*}" >&2; }
fi

TOKEN_LABEL="{{TOKEN_LABEL}}"
MOUNTPOINT="{{MOUNTPOINT}}"

mkdir -p "$MOUNTPOINT"
DEVICE="$(blkid -L "$TOKEN_LABEL" 2>/dev/null || true)"
if [ -z "$DEVICE" ]; then
    warn "Beskar token not detected; skipping initramfs unlock."
    exit 0
fi

mounted=false
cleanup() {
    if $mounted; then
        umount "$MOUNTPOINT" || warn "Failed to unmount Beskar token in initramfs."
    fi
}
trap cleanup EXIT

if ! mount -o ro "$DEVICE" "$MOUNTPOINT"; then
    warn "Unable to mount Beskar token inside initramfs."
    exit 0
fi
mounted=true

if ! zfs load-key -a; then
    warn "zfs load-key -a returned an error; falling back to native prompts."
fi
