#!/bin/bash
# Generated by zfs_beskar_key v{{VERSION}}
set -euo pipefail

if ! command -v warn >/dev/null 2>&1; then
    warn() { echo "[BESKAR] ${*}" >&2; }
fi

TOKEN_LABEL="{{TOKEN_LABEL}}"
MOUNTPOINT="/run/beskar"
CONFIG_PATH="{{CONFIG_PATH}}"
DATASET="{{DATASET}}"
BINARY="{{BINARY_PATH}}"

mkdir -p "$MOUNTPOINT"
DEVICE="$(blkid -L "$TOKEN_LABEL" 2>/dev/null || true)"
if [ -z "$DEVICE" ]; then
    warn "Beskar token not detected; skipping initramfs unlock."
    exit 0
fi

if ! mount -o ro "$DEVICE" "$MOUNTPOINT"; then
    warn "Unable to mount Beskar token inside initramfs."
    exit 0
fi

if [ -x "$BINARY" ]; then
    if ! "$BINARY" auto-unlock --config="$CONFIG_PATH" --dataset="$DATASET" --strict-usb --json; then
        warn "Auto-unlock failed inside initramfs."
    fi
else
    warn "zfs_beskar_key binary unavailable in initramfs."
fi

umount "$MOUNTPOINT" || warn "Failed to unmount Beskar token in initramfs."
