#!/bin/bash
# Generated by zfs_beskar_key v{{VERSION}}

check() {
    require_binaries blkid mount umount || return 1
    return 0
}

depends() {
    echo systemd zfs zfs-crypto
    return 0
}

install() {
    inst_multiple blkid mount umount zfs
    inst_simple "$moddir/{{SCRIPT_NAME}}" "/sbin/{{SCRIPT_NAME}}"
    inst_simple "$moddir/{{SERVICE_NAME}}" "$systemdsystemunitdir/{{SERVICE_NAME}}"
    mkdir -p "$systemdsystemunitdir/initrd.target.wants"
    ln -sf "../{{SERVICE_NAME}}" "$systemdsystemunitdir/initrd.target.wants/{{SERVICE_NAME}}"
}
