#!/bin/bash
# Generated by zfs_beskar_key v{{VERSION}}

depends() {
    echo systemd zfs zfs-crypto
    return 0
}

install() {
    inst_multiple blkid mount umount mkdir mountpoint zfs
    inst_simple "$moddir/{{SCRIPT_NAME}}" "/sbin/{{SCRIPT_NAME}}"
    inst_simple "$moddir/{{SERVICE_NAME}}" "$systemdsystemunitdir/{{SERVICE_NAME}}"
    mkdir -p "$systemdsystemunitdir/initrd-root-fs.target.wants"
    ln -sf "../{{SERVICE_NAME}}" "$systemdsystemunitdir/initrd-root-fs.target.wants/{{SERVICE_NAME}}"
}
